import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lets Get Active",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F9F1E5] dark:bg-[#090606] text-gray-900 dark:text-[#ededed] min-h-screen antialiased">
        {children}
      </body>
    </html>
  );
}
